server:
  port: 8081
vcap:
  services:
    gemfire-config:
      credentials:
        locator1: ec2-34-209-143-245.us-west-2.compute.amazonaws.com
        port1: 10334
      #  locator2: ec2-34-209-143-245.us-west-2.compute.amazonaws.com
      #  port2: 10334
        keystoreUrl: https://github.com/nsarvi/gemfire-cache-service/raw/master/src/main/resources/gemfire-keystore.jks
        keystorePassword: changeit
        truststoreUrl: https://github.com/nsarvi/gemfire-cache-service/raw/master/src/main/resources/gemfire-truststore.jks
        truststorePasswrod: changeit